const actionTypes = {
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
};

export default actionTypes;
